### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by KPGC-YT** [RappyLabyAddons/LabyGPT#14]
![image](https://github.com/RappyLabyAddons/LabyGPT/assets/108461898/8c7ac45e-b57b-49b9-b20e-7bbf03655574)

What does this mean? Sorry my native language isnt english...

**Comment by KPGC-YT** [comment]
and is there any way to solve this problem?

**Comment by SirInfinite** [comment]
same
any way to fix?

**Comment by TheBeaglezBest** [comment]
I might just make my own working version of this ngl

**Comment by RappyTV** [comment]
That's an error from OpenAI and it means that you don't have any credits on your API Key.

**Comment by KPGC-YT** [comment]
What do you mean with that.
Do I need to have a premium Account on OpenAI to use this?
And if not what should we do to fix this?

**Comment by RappyTV** [comment]
Yes unfortunately it's a paid service from OpenAI.
