### ISSUE TITLE
bug: Outdated models

### ISSUE THREAD

**Issue by CookiecopterHD** [RappyLabyAddons/LabyGPT#22]
LabyGPT doesn't seem to work anymore as the models you can select are all outdated and unavailable. Thus there should be an option to select gpt 4o/gpto mini

**Comment by RappyTV** [comment]
Thanks for your issue. I'll work on it right away!

**Comment by RappyTV** [comment]
Alright it's implemented now. You'll have to wait until the update gets reviewed tho.
